[package]
name = "graphdb-rest_api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "^1.24.2", features = ["rt-multi-thread"], optional = true }
tokio-stream = { version = "0.1.17", features = ["net"], optional = true }
libloading = { version = "0.8.6", optional = true }
glob = { version = "0.3.2", optional = true }

[lib]
name = "graphdb_rest_api"
path = "src/lib.rs"

[features]
default = ["client"]
server = ["tokio", "tokio-stream", "libloading", "graphdb-plugin-host", "glob"]
client = ["tokio", "tokio-stream"]
test-suite = ["graphdb-lib/test-suite", "client", "server"]

[dependencies.graphdb-lib]
path = "../lib"
version = "0.1.0"

[dependencies.graphdb-plugin-host]
path = "../plugins/host"
version = "0.1.0"
optional = true
