# storage_daemon_server/sorage_config_rocksdb.yaml
# Configuration for RocksDB storage engine.
# Primarily local, with optional remote connection fields for future use.
storage:
  storage_engine_type: rocksdb
  # Path to local RocksDB data directory (required for local setup).
  path: /opt/graphdb/storage_data/rocksdb
  host: "127.0.0.1"
  port: "8051"
  use_compression: false
  # Optional remote connection fields (uncomment and configure if using a remote RocksDB server).
