storage:
  config_root_directory: "./storage_daemon_server"
  data_directory: "/opt/graphdb/storage_data"
  log_directory: "/var/log/graphdb"
  default_port: 8085
  cluster_range: null
  max_disk_space_gb: 1000
  min_disk_space_gb: 10
  use_raft_for_scale: true
  storage_engine_type: "sled" # Try scalar first, adjust to mapping if needed
  engine_specific_config: null
  max_open_files: 100
