'storage':
  'config-root-directory':
   './storage_daemon_server'
  'data-directory':
   '/opt/graphdb/storage_data'
  'log-directory':
   '/opt/graphdb/logs'
  'default-port':
   8049
  'cluster-range':
   '8049'
  'max-disk-space-gb':
   1000
  'min-disk-space-gb':
   10
  'use-raft-for-scale':
   true
  'storage-engine-type':
   rocks_d_b: ~
  'connection-string':
   ~
  'engine-specific-config':
   ~
  'max-open-files':
   1024
  
