# storage_daemon_server/sorage_config_posgres.yaml
# Configuration for PostgreSQL storage engine.
# Requires connection parameters for local or remote PostgreSQL server.
storage:
  storage_engine_type: postgresql
  # Host address of the PostgreSQL server.
  host: 127.0.0.1
  # Port for PostgreSQL server (default: 5432).
  port: 5432
  # Username for authentication.
  username: graphdb_user
  # Password for authentication.
  password: secure_password
  # Database name to connect to.
  database: graphdb
