# storage_daemon_server/sorage_config_sled.yaml
# Configuration for Sled storage engine.
# Primarily local, with optional remote connection fields for future use.
storage:
  storage_engine_type: sled
  # Path to local Sled data directory (required for local setup).
  use_compression: false
  path: /opt/graphdb/storage_data/sled
  # Optional remote connection fields (uncomment and configure if using a remote Sled server).
  # host: 127.0.0.1
  port: 8052
