# storage_daemon_server/sorage_config_tikv.yaml
# Configuration for Sled storage engine.
# Primarily local, with optional remote connection fields for future use.
storage:
  storage_engine_type: tikv
  # Path to local Sled data directory (required for local setup).
  pd_endpoints: "127.0.0.1:2379"
  host: 127.0.0.1
  port: 2380
  username: "tikv" 
  password: "tikv"
