[app]
version = "0.1.0"

[server]
port = 9002
host = "127.0.0.1"

[rest]
port = 8081
host = "127.0.0.1"

[daemon]
process_name = "graphdb-cli"
user = "graphdbuser"
group = "GraphDBGroup"

[storage]
port = 9000
engine_type = "Sled"

[deployment]
config_root_directory = "/opt/graphdb"

[security]


[paths]


[log]
